### ISSUE TITLE
Need to add these Schema on the website

### ISSUE THREAD

**Issue by sushantkumbhar9** [9ci/9ci.github.io#24]
Hi @jdabal 

Need to add these Schemas on the website before closing tag of HEAD

- Sitelinks Searchbox
- Site Navigation Element
- Voice Search

Schema Recommendation
https://docs.google.com/document/d/1k4anhRkJ1fG3ltMmS3ePCxpUSD8_v5AMCMc0l_P9JFs/edit

**Comment by jdabal** [comment]
All added:

![image](https://user-images.githubusercontent.com/421237/85147530-9e1cd080-b214-11ea-92d3-6a7725135955.png)

**Comment by sushantkumbhar9** [comment]
Hi @jdabal 

There is an error with Voice Search Schema

![image](https://user-images.githubusercontent.com/34949030/85178950-58581a80-b29d-11ea-811d-5778d636e369.png)

**Comment by sushantkumbhar9** [comment]
Hi @jdabal 

There are two codes of Voice Search schema, so we need to remove one code, so remove number code number 1, according to this screenshot.

![image](https://user-images.githubusercontent.com/34949030/85179970-d2899e80-b29f-11ea-84b6-365f1bc383ea.png)

**Comment by jdabal** [comment]
done

**Comment by sushantkumbhar9** [comment]
@jdabal it is not fixed yet

![image](https://user-images.githubusercontent.com/34949030/85466621-d3843e00-b5c7-11ea-858e-6439b112d50f.png)

**Comment by jdabal** [comment]
changed to Webpage, all good now:

![image](https://user-images.githubusercontent.com/421237/85483056-c3e60480-b589-11ea-8336-865a208b1ae7.png)

**Comment by sushantkumbhar9** [comment]
> changed to Webpage, all good now:
> 
> ![image](https://user-images.githubusercontent.com/421237/85483056-c3e60480-b589-11ea-8336-865a208b1ae7.png)

Thanks... It is done now.
